"""add_chr_ml_analytics

Revision ID: 9b3c66ff1bb4
Revises: 
Create Date: 2026-04-13 22:10:09.060481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b3c66ff1bb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chr_ml_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_month', sa.String(length=7), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('location_name', sa.String(length=100), nullable=False),
    sa.Column('kpi_name', sa.String(length=100), nullable=False),
    sa.Column('is_anomaly_client', sa.Boolean(), nullable=True),
    sa.Column('anomaly_score_client', sa.Float(), nullable=True),
    sa.Column('is_anomaly_network', sa.Boolean(), nullable=True),
    sa.Column('anomaly_score_network', sa.Float(), nullable=True),
    sa.Column('arima_forecast', sa.Float(), nullable=True),
    sa.Column('arima_lower_95', sa.Float(), nullable=True),
    sa.Column('arima_upper_95', sa.Float(), nullable=True),
    sa.Column('arima_n_months', sa.Integer(), nullable=True),
    sa.Column('arima_method', sa.String(length=20), nullable=True),
    sa.Column('arima_converged', sa.Boolean(), nullable=True),
    sa.Column('lag_sc_to_chair_r', sa.Float(), nullable=True),
    sa.Column('lag_sc_to_chair_n', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.String(length=50), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_month', 'client_name', 'location_name', 'kpi_name', name='uq_ml_month_client_loc_kpi')
    )
    op.create_index(op.f('ix_chr_ml_analytics_client_name'), 'chr_ml_analytics', ['client_name'], unique=False)
    op.create_index(op.f('ix_chr_ml_analytics_kpi_name'), 'chr_ml_analytics', ['kpi_name'], unique=False)
    op.create_index(op.f('ix_chr_ml_analytics_location_name'), 'chr_ml_analytics', ['location_name'], unique=False)
    op.create_index(op.f('ix_chr_ml_analytics_run_month'), 'chr_ml_analytics', ['run_month'], unique=False)
    op.create_index('ix_ml_anomaly_flags', 'chr_ml_analytics', ['is_anomaly_client', 'is_anomaly_network', 'run_month'], unique=False)
    op.create_index('ix_ml_client_month', 'chr_ml_analytics', ['client_name', 'run_month'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ml_client_month', table_name='chr_ml_analytics')
    op.drop_index('ix_ml_anomaly_flags', table_name='chr_ml_analytics')
    op.drop_index(op.f('ix_chr_ml_analytics_run_month'), table_name='chr_ml_analytics')
    op.drop_index(op.f('ix_chr_ml_analytics_location_name'), table_name='chr_ml_analytics')
    op.drop_index(op.f('ix_chr_ml_analytics_kpi_name'), table_name='chr_ml_analytics')
    op.drop_index(op.f('ix_chr_ml_analytics_client_name'), table_name='chr_ml_analytics')
    op.drop_table('chr_ml_analytics')
    # ### end Alembic commands ###
