var EM = '\u2014'
var MID = '\u00b7'

export async function copyAsEmail(messageContent, clinicName, month) {
  var parts = ['Clinic Performance Update']
  if (clinicName) parts.push(EM + ' ' + clinicName)
  if (month) parts.push('(' + month + ')')
  var subject = parts.join(' ')

  var body = messageContent.replace(
    /```recharts[\s\S]*?```/g,
    '[Chart ' + EM + ' open the dashboard to view the visual]'
  )

  var formatted = [
    'Subject: ' + subject,
    '',
    body,
    '',
    EM + EM + EM,
    'Generated by IntelliSite AI ' + MID + ' Validate all figures with your clinical team before sharing.',
  ].join('\n')

  await navigator.clipboard.writeText(formatted)
}
